# Site settings
title: Giles Dron
email: giles@dron.email
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ecstatic-varahamihira-1dad71.netlify.com/" # the base hostname & protocol for your site
twitter_username: thedrons
github_username:  gilesdron

# Build settings
markdown: kramdown
future: true
include: /_redirects
